version: "2"
services:
  deploy-to-s3:
    extends:
      service: working_dir
      file: ../.common/docker-compose.yml
    image: repworth/aws-cli:aws-cli1.10
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=us-west-2
    entrypoint: |
      aws s3 sync . s3://urlable-website \
      --delete \
      --exclude ".git/*" \
      --exclude "node_modules/*" \
      --exclude "jspm_packages/*" \
      --exclude ".dev-op-spec/*" \
      --include "jspm_packages/system.js*"
